### ISSUE TITLE
Remove lose() function

### ISSUE THREAD

**Issue by ianrahman** [learn-co-curriculum/swift-EnumsFun-lab#2]
Seems entirely redundant if cards have already been removed from the hand in the `flip()` function

**Comment by JimCampagno** [comment]
Hmm. Interesting, have to do some digging to see exactly what you mean by this. I forget the flow of this app to be honest. If it's on the tip of your tongue (which it probably isn't because this was written on Oct 7th, would you mind changing that?).

@ianrahman
